# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'deploy ubuntu machine'
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN (ebdc60c1-a859-4b24-914c-e268d086e5a5)'
    resourceGroupName: ubuntu
    location: 'Central US'
    csmFile: '$(System.DefaultWorkingDirectory)/_Velislav-Dikov_tailspin/azuredeploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/_Velislav-Dikov_tailspin/azuredeploy.parameters.json'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
